# Generated by Django 3.2.18 on 2023-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('SV', 'Super Visor'), ('M', 'Manager'), ('SS', 'senior sales'), ('W', 'worker')], max_length=2, verbose_name='position'),
        ),
    ]
