# Generated by Django 3.2.18 on 2023-08-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_dashbord', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_dashbord.market'),
        ),
    ]
