# Generated by Django 3.2.18 on 2023-08-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_dashbord', '0001_initial'),
        ('users', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, verbose_name='возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars/%Y-%m-%d/', verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='market_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_dashbord.market', verbose_name='market_number'),
        ),
    ]
