# Generated by Django 3.2.18 on 2023-08-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_dashbord', '0001_initial'),
        ('users', '0004_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars/%Y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Пользователь с таким email уже есть'}, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='market_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_dashbord.market', verbose_name='Номер магазина'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('SV', 'Super Visor'), ('M', 'Manager'), ('SS', 'senior sales'), ('W', 'worker')], max_length=2, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким telephone уже есть'}, max_length=11, unique=True, verbose_name='Телефон'),
        ),
    ]
