# Generated by Django 3.2.18 on 2023-06-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_dashbord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='products/%Y-%m-%d/', verbose_name='Product')),
                ('date_best_before', models.DateTimeField()),
                ('barcode', models.CharField(blank=True, max_length=15)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('write_off', models.BooleanField(default=False)),
                ('number_of_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_dashbord.market')),
            ],
            options={
                'ordering': ['-date_best_before'],
            },
        ),
    ]
