# Generated by Django 3.2.18 on 2023-08-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market_dashbord', '0001_initial'),
        ('product', '0002_product_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=15, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_best_before',
            field=models.DateField(verbose_name='Годен до какого числа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products/%Y-%m-%d/', verbose_name='Фото продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Просрочен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_dashbord.market', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='write_off',
            field=models.BooleanField(default=False, verbose_name='Списан'),
        ),
    ]
