# Generated by Django 3.2.18 on 2023-07-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_date_best_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='products/%Y-%m-%d/', verbose_name='Product'),
        ),
    ]
