# Generated by Django 3.2.18 on 2023-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products/%Y-%m-%d/', verbose_name='Product'),
        ),
    ]
