# Generated by Django 3.2.18 on 2023-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_dashbord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='number_market',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
